disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules:
  - empty_count
force_cast: 
  severity: warning
line_length: 120
custom_rules:
  no_explicit_self: # rule identifier
    name: "No explicit self" # rule name. optional.
    regex: "([n,N]inja)" # matching pattern
    message: "Don't use explicit self when it is not needed." # violation message. optional.
    severity: error # violation severity. optional.
